image: maven:3.6.3-jdk-11

stages:
  - Test

Test:
  stage: Test
  script:
    - mvn clean install
  artifacts:
    when: always
    paths:
      - target/JUnitReport/
    expire_in: 1 week
    reports:
      junit: target/JUnitReport/report.xml
  only:
    - master